name: learn-github-actions
on: 
  push: 
    branches: [ test ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Aabill/Aabill.git
          token: ${{ secrets.GH_TOKEN }}
          ref: main
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
    env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}