name: Instagram Request
on:
  push:
    branches:
      - instagram
jobs:
  instagram:
    runs-on: ubuntu-latest
    name: Test curl
    steps:
    - name: Checkout current repository to Master branch
      uses: actions/checkout@v1
    - name: curl
      uses: wei/curl@v1
      with: 
        args: -X POST -F "client_id=2805644083092506" -F "client_secret=1ce1bfc5e8ac241c8a39b0f93b6b4adf" -F "grant_type=authorization_code" -F "redirect_uri=https://aabill.github.io/Aabill/" -F "code=AQCjdF2qtzeYuJ7tNfv_iWTKs-zFT_NnsS_NJvesL__Yhga7DF3521KAzOzfFzTM69NDLRCnia5p-3YFFZU9kJxhvOnWZq-KP-bR6t2Itk4ll6RVGRjxTIRaEtAZXHfv62iLG4UsHANnA2yJb815TW0BRZLTG1uMBQ1ACgp0ts_xO5eC_pJOIcxwdcYX9QBd0TRAp8gh9krpdMLm3rWa1x27ovI4UPoDtjeoei1IUNzzQA" https://api.instagram.com/oauth/access_token