name: Instagram Request
on:
  push:
    branches:
      - instagram
jobs:
  instagram:
    runs-on: ubuntu-18.04
    name: Instagram Test
    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          file_name: .env
          envkey_SOME_KEY: "Some Text ngay pimans ENV"
          directory: /    
      - name: Run JS Script
        run: node ./.github/scripts/index.js
        shell: bash