name: Instagram Request
on:
  push:
    branches:
      - instagram
jobs:
  instagram:
    runs-on: ubuntu-18.04
    name: Instagram Test
    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Run JS Script
        env:
          SOME_TEXT: Testing Some Text env
        run: node ./.github/scripts/index.js
        shell: bash