name: Instagram Request
on:
  push:
    branches:
      - instagram
jobs:
  instagram:
    runs-on: ubuntu-latest
    name: Test curl
    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TEST: 'Testing yords Env Test'
          file_name: .env
      - name: Run JS Script
        run: node ./.github/scripts/index.js
        shell: bash